### PR TITLE
Make the replacement pattern configurable.

### PR DESCRIPTION
**Pull request by Tom32i**
Make the `[#PR]` replacement token customizable through configuration.

### CODE REVIEW

**Comment by Tom32i** [comment]
Hi @matyas-igor ! 
I have the same needs in my company workflow (injecting PR id in the body of a PR for preview urls).
But we use a different token.

Would you consider this PR allowing a custom replacement token?

**Comment by matyas-igor** [comment]
Hi @Tom32i, thanks a lot for your contribution! I love it and I'm totally going to merge it, I only have one comment here: usually converting string to regexp requires some characters escaping and I see that you'd proposed to do it manually.

What do you think about using a pre-defined function to do this? Like for example this one: https://github.com/sindresorhus/escape-string-regexp/blob/main/index.js

Then a pattern parameter will look like `[#PR]` and no escaping will be needed

**Comment by Tom32i** [comment]
If the goal is to have a simple string replacement, then I'm all for it. 
But why not drop the Regex entirely in that case? The [replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) method supports string replacement.

I've updated my PR in that direction :)

**Comment by matyas-igor** [comment]
Thanks! That would work quite well too :) Initially, regexp was used for global matching, and I think it makes sense to drop it completely since replacements are not getting processed in any way.

**Comment by Tom32i** [comment]
Thanks! Could you make a new release? I'd love to give it a try :)

**Comment by matyas-igor** [comment]
Sure, just released, please feel free to try it out :)

**Pull request merged**
